name: Deploy Next.js App to Tencent Cloud

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to Tencent Cloud
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USERNAME  }}
        key: ${{ secrets.PRIVATE_KEY }}
        source: ".next,public,package.json,next.config.js"
        target: "/var/www/nextjs-app"
        
    - name: Restart application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USERNAME  }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd /var/www/nextjs-app
          npm install --production
          pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- start